version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminsecret
      POSTGRES_DB: ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://admin:adminsecret@postgres:5432/ecommerce
      HASURA_GRAPHQL_ADMIN_SECRET: newproject
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
    restart: always
volumes:
  pgdata: